import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'masariLanguage'

const translations = {
  en: {
    app: {
      language: 'العربية',
      logout: 'Logout',
      brand: 'مساري',
    },
    nav: {
      dashboard: 'Dashboard',
      job: 'Job Details',
      roadmap: 'Roadmap',
      courseAnalysis: 'Course Analysis',
    },
    login: {
      badge: 'Masari Platform',
      heading: 'Welcome back, future-ready student.',
      subtitle:
        'Sign in with your Prince Sattam Bin Abdulaziz University student account.',
      welcomePrompt: 'Welcome to Masari. Your smart path from university courses to real market opportunities starts here.',
      cardTitle: 'Student Login',
      allowedEmail: 'Allowed email format:',
      dummyAccounts: 'Dummy accounts:',
      passwordHint: 'Password:',
      email: 'University Email',
      password: 'Password',
      emailPlaceholder: 'e.g. ahmad.2022@std.psau.edu.sa',
      passwordPlaceholder: 'Enter password',
      login: 'Login',
      signUp: 'Sign Up',
      featureOne: 'PSAU student authentication',
      featureTwo: 'Career dashboard and roadmap',
      requiredError: 'Please enter your university email and password.',
      invalidDomain: 'Use your university email ending with @std.psau.edu.sa to sign in.',
      invalidCredentials: 'Invalid email or password. Try one of the dummy student accounts.',
    },
    dashboard: {
      badge: 'Student Dashboard',
      title: 'Recommended Jobs for Your Major',
      subtitle: 'Welcome {{name}}. Explore careers aligned with your major and current academic profile.',
      university: 'University',
      college: 'College',
      major: 'Major',
      collegeYear: 'College Year',
      semester: 'Semester',
      studentId: 'Student ID',
      gpa: 'GPA',
      careerGoal: 'Career Goal',
      roadmapCompletion: 'Roadmap Completion in Your Profile',
      roadmapCompletionHint: 'Your checked courses from the roadmap appear here to track real progress over time.',
      completedCoursesList: 'Courses you marked as done',
      completedSearchPlaceholder: 'Search by course name or code',
      noCoursesMatchSearch: 'No completed courses match this search.',
      continueRoadmap: 'Continue this roadmap',
      tabProgress: 'Progress Tracker',
      tabCareers: 'Career Suggestions',
      progressSectionTitle: 'Tracked Completed Courses',
      progressSectionHint: 'Review what you finished in the selected roadmap and continue from where you stopped.',
      noCompletedCoursesYet: 'No courses marked as done yet in this roadmap.',
      unnamedRoadmap: 'Unnamed roadmap',
      roadmapName: 'Roadmap name',
      roadmapMajor: 'Major',
      roadmapLastUpdate: 'Last update',
      noRoadmapProgress: 'No roadmap progress yet',
      overallCompletion: 'Overall completion',
      careersSectionTitle: 'Recommended Careers',
      careersSectionHint: 'These are suggested target careers for your major. Choose one to open details and generate or continue its roadmap.',
      applicationPriority: 'Application Priority',
      applyCareer: 'Apply for this career',
      noCareers: 'No careers found for this major. Please adjust the dummy profile later if needed.',
    },
    job: {
      notFoundTitle: 'Career Not Found',
      notFoundDesc: 'Please return to the dashboard and select an available career.',
      goDashboard: 'Go to Dashboard',
      badge: 'Job Details',
      yourCollege: 'Your College',
      descriptionTitle: 'Job Description',
      personalizedDesc: 'This recommendation is personalized from your selected college and major to maximize your internship readiness.',
      skillsTitle: 'Required Skills',
      prepareTitle: 'Ready to prepare for this role?',
      prepareDesc: 'Generate a personalized learning roadmap with milestones, courses, and projects tailored to this job opportunity.',
      generateRoadmap: 'Generate Career Roadmap',
    },
    roadmap: {
      unavailableTitle: 'Roadmap Unavailable',
      unavailableDesc: 'Please choose a career from dashboard first to generate a roadmap.',
      guestTitle: 'Build Your Roadmap Without Login',
      guestDesc: 'Choose your major and current level first, then we recommend the closest careers and generate your roadmap instantly.',
      psauCollege: 'College of Engineering and Computer Science - Prince Sattam Bin Abdulaziz University',
      servingCollege: 'Currently serving',
      collegePlaceholder: 'Enter your college name',
      major: 'Major',
      yearLabel: 'Year',
      firstSemester: 'First Semester',
      secondSemester: 'Second Semester',
      showCareers: 'Show Closest Careers',
      closestCareers: 'Closest careers for your major',
      backToStepOne: 'Back to Major and Level',
      selectCareer: 'Select Career Path',
      selectCareerPlaceholder: 'Choose a career role',
      generateGuestRoadmap: 'Generate Roadmap Now',
      guestStudent: 'Guest Student',
      notProvided: 'Not Provided',
      careerRoadmap: 'Career Roadmap',
      roadmapFor: 'Roadmap for {{title}}',
      generatedFrom: 'Generated from your profile: {{major}}{{college}}. Compare each semester course against role requirements and close skill gaps.',
      student: 'Student',
      involvedCourses: 'Involved Courses',
      remainingCourses: 'Remaining Courses',
      current: 'Current',
      completed: 'Completed',
      ongoing: 'Ongoing',
      remaining: 'Remaining',
      matchToJob: 'Match to job requirements',
      detectedGaps: 'Detected Gaps',
      extraResources: 'Extra Resources',
      importantForRole: 'Important for this role',
      importantCoursesFocus: 'Important focus courses',
      progressTitle: 'Your roadmap completion progress',
      progressHint: 'Mark any finished course and your profile completion will update automatically.',
      markAsDone: 'Mark as done',
      viewCourseAnalysis: 'View AI Course Analysis',
      courseAiPanelTitle: 'Interactive Course Intelligence Panel',
      courseAiPanelHint: 'Click any course card in the roadmap timeline to see deeper market analysis and tailored resources.',
      selectCourseHint: 'Select a course from the roadmap above to show AI insights, market need score, and external resources.',
      marketNeedLevel: 'Market need score for this course',
      courseRelationship: 'Linked target role',
      courseDescriptionLabel: 'Course description',
      courseContentSkills: 'Course content and skills',
      matchingMarketSkills: 'Skills aligned with market needs',
      marketGapSkills: 'Gap skills to strengthen',
      requiredSkillsWhyTitle: 'Why these required skills matter',
      requiredSkillsWhyHint: 'Each skill below is requested by the target role. This explanation helps the student understand why extra learning modules are important.',
      skillCovered: 'Covered in this course',
      skillMissing: 'Needs extra learning',
      noDirectMatch: 'No direct market skill match yet for this course.',
      noGapNow: 'Great! No major gap detected for this course now.',
      recommendedExternalResources: 'AI-suggested external resources (articles, videos, courses)',
      closeDetails: 'Close',
      aiModeGap: 'Gap Analysis',
      aiModeFull: 'Full Market-Ready Plan',
      coverageHigh: 'University coverage is strong for this course compared with market needs.',
      coverageMedium: 'University coverage is moderate; a few market topics should be added.',
      coverageLow: 'University coverage is limited for current market demands in this role.',
      aiRecommendationNarrative: 'AI interpretation',
      universityContentLabel: 'The university currently teaches',
      marketMissingLabel: 'Market expects additional focus on',
      addedContentLabel: 'Suggested action: add practical tasks, case-based assignments, and updated market tools for these gaps.',
      fullPlanTitle: 'Comprehensive content plan for market readiness',
      addModulePrefix: 'Add learning module for',
    },
    course: {
      badge: 'Masari Course Analysis',
      title: 'Compare Courses with Job Skill Requirements',
      subtitle: 'Understand how your university courses align with real industry roles, identify skill gaps, and follow recommended learning resources.',
      searchPlaceholder: 'Search by course name or code',
      majorFilter: 'Major',
      semesterFilter: 'Semester',
      allSemesters: 'All Semesters',
      marketRequirementsTitle: 'Saudi Market Requirements',
      companiesContributing: 'Companies contributing requirements',
      currentSemester: 'Current Semester',
      activeRequirements: 'Active Requirements',
      requirementWindow: 'Semester Window',
      companyWeight: 'Company Weight',
      role: 'Target Role',
      demandSkills: 'Demanded Skills',
      details: 'Details',
      companiesSuggesting: 'Companies Suggesting This Course',
      noCompanyMatches: 'No matching companies for this course at the current level.',
      totalCourses: 'Total Courses',
      averageMatch: 'Average Match',
      topCompanies: 'Top Market Companies',
      sortHigh: 'Sort: Match High to Low',
      sortLow: 'Sort: Match Low to High',
      sortAZ: 'Sort: Course A-Z',
      sortSemester: 'Sort: Semester Asc',
      track: 'Track',
      matchingPercentage: 'Matching Percentage',
      skillsGained: 'Skills Gained',
      missingSkills: 'Missing Skills',
      suggestedResources: 'Suggested Learning Resources',
      closeDetails: 'Close Details',
      noCourses: 'No courses found for the selected filter.',
      all: 'All',
    },
    landing: {
      demo: 'Request Demo',
      badge: 'PSAU Career Platform',
      title: 'Masari Platform for PSAU Students',
      subtitle: 'A smart guide for students of the College of Engineering and Computer Science to connect major courses with market-ready careers.',
      introMessage: 'Welcome to Masari. This platform currently serves PSAU students in Software Engineering, Computer Science, Information Systems, and Computer Engineering.',
      welcomeHeadline: 'Welcome to Masari - Official platform for PSAU Engineering and Computer Science students',
      welcomeSubline: 'Choose your major, select your level, discover the closest careers, and get a focused roadmap with key courses and market gap resources.',
      welcomeLineOne: 'Start with your major and academic level to get personalized role matching.',
      welcomeLineTwo: 'Track important courses, close market gaps, and build your roadmap semester by semester.',
      statMajors: 'Supported Majors',
      statCareers: 'Suggested Career Paths',
      statRoadmap: 'Personalized Roadmap',
      primary: 'Start Building My Roadmap',
      secondary: 'Sign In as Student',
      semester: 'This Semester',
      course: 'Data Structures and Algorithms',
      suggestedRole: 'Suggested role',
      role: 'Backend Engineer Intern',
      gapTitle: 'Skill gap to close',
      gap: 'API design and system thinking',
      why: 'Why Students Choose Masari',
      featureOneTitle: 'Course-to-Job Mapping',
      featureOneDesc: 'Instantly see which careers align with your current subjects and degree pathway.',
      featureTwoTitle: 'Personalized Skill Plan',
      featureTwoDesc: 'AI recommends projects, certifications, and electives to close skill gaps before graduation.',
      featureThreeTitle: 'Opportunity Matching',
      featureThreeDesc: 'Discover internships and entry roles that match your coursework, interests, and progress level.',
      ctaTitle: 'Build your future while you study.',
      ctaDesc: 'Join Masari and get AI-powered career guidance that evolves with every semester.',
      ctaButton: 'Join Masari Free',
      footerOne: '2026 Masari Platform. Built for ambitious students.',
      footerTwo: 'Connect courses, skills, and career opportunities in one place.',
    },
  },
  ar: {
    app: {
      language: 'English',
      logout: 'تسجيل الخروج',
      brand: 'مساري',
    },
    nav: {
      dashboard: 'لوحة التحكم',
      job: 'تفاصيل الوظيفة',
      roadmap: 'الخريطة المهنية',
      courseAnalysis: 'تحليل المقررات',
    },
    login: {
      badge: 'منصة مساري',
      heading: 'مرحباً بعودتك، أيها الطالب المستعد للمستقبل.',
      subtitle: 'سجّل الدخول باستخدام حسابك الطلابي في جامعة الأمير سطام بن عبدالعزيز.',
      welcomePrompt: 'مرحباً بك في مساري. طريقك الذكي من مقررات الجامعة إلى فرص سوق العمل يبدأ من هنا.',
      cardTitle: 'دخول الطالب',
      allowedEmail: 'صيغة البريد المسموحة:',
      dummyAccounts: 'الحسابات التجريبية:',
      passwordHint: 'كلمة المرور:',
      email: 'البريد الجامعي',
      password: 'كلمة المرور',
      emailPlaceholder: 'مثال: ahmad.2022@std.psau.edu.sa',
      passwordPlaceholder: 'أدخل كلمة المرور',
      login: 'تسجيل الدخول',
      signUp: 'إنشاء حساب',
      featureOne: 'توثيق طلاب جامعة الأمير سطام',
      featureTwo: 'لوحة مهنية وخارطة طريق',
      requiredError: 'يرجى إدخال البريد الجامعي وكلمة المرور.',
      invalidDomain: 'يجب استخدام بريد الجامعة المنتهي بـ @std.psau.edu.sa.',
      invalidCredentials: 'البريد أو كلمة المرور غير صحيحة. جرّب أحد الحسابات التجريبية.',
    },
    dashboard: {
      badge: 'لوحة الطالب',
      title: 'الوظائف المناسبة لتخصصك',
      subtitle: 'مرحباً {{name}}. استكشف الوظائف المتوافقة مع تخصصك وملفك الأكاديمي الحالي.',
      university: 'الجامعة',
      college: 'الكلية',
      major: 'التخصص',
      collegeYear: 'السنة الدراسية',
      semester: 'الفصل الدراسي',
      studentId: 'الرقم الجامعي',
      gpa: 'المعدل',
      careerGoal: 'الهدف المهني',
      roadmapCompletion: 'نسبة إكمال الخريطة في ملفك',
      roadmapCompletionHint: 'أي مقرر تضع عليه علامة صح في الخريطة سيظهر هنا لمتابعة تقدمك الفعلي.',
      completedCoursesList: 'المقررات التي أنهيتها',
      completedSearchPlaceholder: 'ابحث باسم المقرر أو رمزه',
      noCoursesMatchSearch: 'لا توجد مقررات مكتملة مطابقة لنتيجة البحث.',
      continueRoadmap: 'متابعة هذه الخريطة',
      tabProgress: 'متابعة التقدم',
      tabCareers: 'الوظائف المقترحة',
      progressSectionTitle: 'المقررات المكتملة في الخريطة',
      progressSectionHint: 'راجع ما أنهيته في الخريطة المختارة وكمل من آخر نقطة وصلت لها.',
      noCompletedCoursesYet: 'لم يتم تحديد أي مقرر كمكتمل في هذه الخريطة بعد.',
      unnamedRoadmap: 'خريطة بدون اسم',
      roadmapName: 'اسم الخريطة',
      roadmapMajor: 'التخصص',
      roadmapLastUpdate: 'آخر تحديث',
      noRoadmapProgress: 'لا يوجد تقدم مسجل في الخريطة بعد',
      overallCompletion: 'الإكمال الكلي',
      careersSectionTitle: 'المسارات المهنية المقترحة',
      careersSectionHint: 'هذه مسارات وظيفية مقترحة حسب تخصصك. اختر أي مسار لعرض التفاصيل وإنشاء الخريطة أو استكمالها.',
      applicationPriority: 'أولوية التقديم',
      applyCareer: 'التقديم على هذا المسار',
      noCareers: 'لا توجد وظائف مطابقة لهذا التخصص حالياً. يمكنك تعديل البيانات التجريبية لاحقاً.',
    },
    job: {
      notFoundTitle: 'الوظيفة غير موجودة',
      notFoundDesc: 'يرجى العودة إلى لوحة التحكم واختيار وظيفة متاحة.',
      goDashboard: 'العودة إلى اللوحة',
      badge: 'تفاصيل الوظيفة',
      yourCollege: 'كليتك',
      descriptionTitle: 'وصف الوظيفة',
      personalizedDesc: 'تم تخصيص هذا الترشيح بناءً على كليتك وتخصصك لزيادة جاهزيتك للتدريب والعمل.',
      skillsTitle: 'المهارات المطلوبة',
      prepareTitle: 'هل أنت مستعد للاستعداد لهذه الوظيفة؟',
      prepareDesc: 'أنشئ خارطة طريق تعليمية مخصصة تتضمن مراحل ومقررات ومشاريع ملائمة لهذه الفرصة.',
      generateRoadmap: 'إنشاء الخريطة المهنية',
    },
    roadmap: {
      unavailableTitle: 'الخريطة غير متاحة',
      unavailableDesc: 'يرجى اختيار وظيفة من لوحة التحكم أولاً لإنشاء الخريطة.',
      guestTitle: 'أنشئ خريطتك المهنية بدون تسجيل دخول',
      guestDesc: 'اختر تخصصك ومستواك الدراسي أولاً، ثم ستظهر لك الوظائف الأقرب لتخصصك وبعدها ننشئ لك خريطة مهنية مباشرة.',
      psauCollege: 'كلية الهندسة وعلوم الحاسب - جامعة الأمير سطام بن عبدالعزيز',
      servingCollege: 'الخدمة الحالية',
      collegePlaceholder: 'اكتب اسم الكلية',
      major: 'التخصص',
      yearLabel: 'السنة',
      firstSemester: 'الفصل الأول',
      secondSemester: 'الفصل الثاني',
      showCareers: 'إظهار الوظائف الأقرب',
      closestCareers: 'الوظائف الأقرب لتخصصك',
      backToStepOne: 'الرجوع لاختيار التخصص والمستوى',
      selectCareer: 'اختر المسار الوظيفي',
      selectCareerPlaceholder: 'اختر وظيفة مناسبة',
      generateGuestRoadmap: 'إنشاء الخريطة الآن',
      guestStudent: 'طالب زائر',
      notProvided: 'غير محدد',
      careerRoadmap: 'الخريطة المهنية',
      roadmapFor: 'الخريطة المهنية لـ {{title}}',
      generatedFrom: 'تم الإنشاء بناءً على ملفك: {{major}}{{college}}. قارن كل مقرر بمتطلبات الوظيفة وأغلق فجوات المهارات.',
      student: 'الطالب',
      involvedCourses: 'المقررات التي درسها',
      remainingCourses: 'المقررات المتبقية',
      current: 'الحالي',
      completed: 'مكتمل',
      ongoing: 'جاري',
      remaining: 'متبقي',
      matchToJob: 'نسبة التطابق مع الوظيفة',
      detectedGaps: 'الفجوات المكتشفة',
      extraResources: 'موارد إضافية',
      importantForRole: 'مقرر مهم لهذه الوظيفة',
      importantCoursesFocus: 'عدد المقررات المهمة التي يجب التركيز عليها',
      progressTitle: 'نسبة إكمالك للخريطة المهنية',
      progressHint: 'ضع علامة صح على أي مقرر أنهيته وسيتم تحديث النسبة في ملفك تلقائياً.',
      markAsDone: 'تحديد كمكتمل',
      viewCourseAnalysis: 'عرض تحليل المقرر بالذكاء الاصطناعي',
      courseAiPanelTitle: 'لوحة تحليل المقرر التفاعلية',
      courseAiPanelHint: 'اضغط على أي مقرر في الخريطة لعرض تحليل أعمق لاحتياج السوق والموارد المناسبة.',
      selectCourseHint: 'اختر مقررًا من الخريطة بالأعلى ليظهر تحليل الذكاء الاصطناعي ونسبة احتياج السوق والموارد الخارجية.',
      marketNeedLevel: 'نسبة احتياج سوق العمل لهذا المقرر',
      courseRelationship: 'الوظيفة المرتبطة',
      courseDescriptionLabel: 'وصف المقرر',
      courseContentSkills: 'محتوى المقرر والمهارات',
      matchingMarketSkills: 'المهارات المتوافقة مع احتياج السوق',
      marketGapSkills: 'المهارات المطلوب تقويتها لسد الفجوة',
      requiredSkillsWhyTitle: 'لماذا هذه المهارات المطلوبة مهمة؟',
      requiredSkillsWhyHint: 'كل مهارة بالأسفل مطلوبة من الوظيفة المستهدفة، والشرح يساعد الطالب على فهم سبب الحاجة للمهارات الإضافية.',
      skillCovered: 'مغطاة في هذا المقرر',
      skillMissing: 'تحتاج تعلم إضافي',
      noDirectMatch: 'لا يوجد تطابق مباشر قوي مع مهارات السوق لهذا المقرر حالياً.',
      noGapNow: 'ممتاز! لا توجد فجوة كبيرة حالياً في هذا المقرر.',
      recommendedExternalResources: 'موارد خارجية مقترحة بالذكاء الاصطناعي (مقالات، فيديوهات، كورسات)',
      closeDetails: 'إغلاق',
      aiModeGap: 'تحليل الفجوة',
      aiModeFull: 'خطة شاملة جاهزة لسوق العمل',
      coverageHigh: 'تغطية الجامعة قوية في هذا المقرر مقارنة باحتياج السوق.',
      coverageMedium: 'تغطية الجامعة متوسطة، وهناك موضوعات سوقية تحتاج إضافة.',
      coverageLow: 'تغطية الجامعة محدودة أمام احتياج السوق الحالي لهذه الوظيفة.',
      aiRecommendationNarrative: 'تفسير الذكاء الاصطناعي',
      universityContentLabel: 'الجامعة تدرّس حالياً',
      marketMissingLabel: 'سوق العمل يحتاج تركيزاً إضافياً على',
      addedContentLabel: 'الإضافة المقترحة: مهام عملية، وحالات تطبيقية، وأدوات سوق حديثة لتغطية هذه الفجوات.',
      fullPlanTitle: 'خطة محتوى شاملة لتجهيزك لسوق العمل',
      addModulePrefix: 'إضافة وحدة تعلم خاصة بـ',
    },
    course: {
      badge: 'تحليل مقررات مساري',
      title: 'قارن المقررات مع متطلبات الوظائف',
      subtitle: 'افهم كيف تتوافق مقرراتك الجامعية مع الأدوار المهنية الحقيقية وحدد فجوات المهارات واتبع الموارد المقترحة.',
      searchPlaceholder: 'ابحث باسم المقرر أو رمزه',
      majorFilter: 'التخصص',
      semesterFilter: 'الفصل',
      allSemesters: 'كل الفصول',
      marketRequirementsTitle: 'متطلبات سوق العمل السعودي',
      companiesContributing: 'الشركات التي وضعت هذه المتطلبات',
      currentSemester: 'الفصل الحالي',
      activeRequirements: 'المتطلبات النشطة',
      requirementWindow: 'نطاق الفصول',
      companyWeight: 'وزن الشركة',
      role: 'الدور الوظيفي المستهدف',
      demandSkills: 'المهارات المطلوبة',
      details: 'التفاصيل',
      companiesSuggesting: 'الشركات التي تقترح هذا المقرر',
      noCompanyMatches: 'لا توجد شركات مطابقة لهذا المقرر في المستوى الحالي.',
      totalCourses: 'إجمالي المقررات',
      averageMatch: 'متوسط التطابق',
      topCompanies: 'أبرز شركات السوق',
      sortHigh: 'الترتيب: أعلى تطابق إلى أقل',
      sortLow: 'الترتيب: أقل تطابق إلى أعلى',
      sortAZ: 'الترتيب: المقررات أبجدياً',
      sortSemester: 'الترتيب: حسب الفصل تصاعدياً',
      track: 'المسار',
      matchingPercentage: 'نسبة التطابق',
      skillsGained: 'المهارات المكتسبة',
      missingSkills: 'المهارات الناقصة',
      suggestedResources: 'الموارد التعليمية المقترحة',
      closeDetails: 'إغلاق التفاصيل',
      noCourses: 'لا توجد مقررات مطابقة للفلترة المحددة.',
      all: 'الكل',
    },
    landing: {
      demo: 'اطلب عرضاً تجريبياً',
      badge: 'منصة مساري لجامعة الأمير سطام',
      title: 'منصة مساري لطلاب جامعة الأمير سطام',
      subtitle: 'منصة ذكية تساعد طلاب كلية الهندسة وعلوم الحاسب على ربط المقررات بالوظائف الأقرب لسوق العمل.',
      introMessage: 'مرحباً بك في مساري. المنصة حالياً تخدم طلاب تخصصات: هندسة البرمجيات، علوم الحاسب، نظم المعلومات، وهندسة الحاسب.',
      welcomeHeadline: 'مرحباً بك في مساري - المنصة الرسمية لطلاب كلية الهندسة وعلوم الحاسب بجامعة الأمير سطام',
      welcomeSubline: 'اختر تخصصك، حدد مستواك، اكتشف الوظائف الأقرب، واحصل على خريطة مركزة بالمقررات المهمة وموارد سد فجوات السوق.',
      welcomeLineOne: 'ابدأ باختيار تخصصك ومستواك الدراسي لتحصل على وظائف مقترحة بشكل مخصص.',
      welcomeLineTwo: 'تابع المقررات المهمة، وأغلق فجوات السوق، وابنِ خريطتك المهنية فصلًا بعد فصل.',
      statMajors: 'التخصصات المدعومة',
      statCareers: 'المسارات الوظيفية المقترحة',
      statRoadmap: 'خريطة مهنية مخصصة',
      primary: 'ابدأ بناء الخريطة المهنية',
      secondary: 'تسجيل دخول الطالب',
      semester: 'هذا الفصل',
      course: 'هياكل البيانات والخوارزميات',
      suggestedRole: 'الوظيفة المقترحة',
      role: 'متدرب مهندس برمجيات خلفية',
      gapTitle: 'فجوة مهارية تحتاج إغلاقها',
      gap: 'تصميم الواجهات البرمجية والتفكير المنظومي',
      why: 'لماذا يختار الطلاب منصة مساري',
      featureOneTitle: 'ربط المقررات بالوظائف',
      featureOneDesc: 'اعرف فوراً الوظائف التي تتوافق مع مقرراتك الحالية وخطتك الدراسية.',
      featureTwoTitle: 'خطة مهارية مخصصة',
      featureTwoDesc: 'يقترح الذكاء الاصطناعي مشاريع وشهادات ومقررات اختيارية لسد الفجوات قبل التخرج.',
      featureThreeTitle: 'مطابقة الفرص',
      featureThreeDesc: 'اكتشف التدريبات والوظائف المبتدئة المناسبة لمقرراتك واهتماماتك ومستواك الحالي.',
      ctaTitle: 'ابنِ مستقبلك أثناء الدراسة.',
      ctaDesc: 'انضم إلى مساري واحصل على إرشاد مهني ذكي يتطور مع كل فصل دراسي.',
      ctaButton: 'انضم إلى مساري مجاناً',
      footerOne: 'منصة مساري 2026. صممت للطلاب الطموحين.',
      footerTwo: 'اربط بين المقررات والمهارات والفرص المهنية في مكان واحد.',
    },
  },
}

const LanguageContext = createContext(null)

function getValue(object, path) {
  return path.split('.').reduce((current, key) => current?.[key], object)
}

function interpolate(text, values = {}) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replace(new RegExp(`{{${key}}}`, 'g'), value ?? ''),
    text
  )
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem(STORAGE_KEY)
    return saved === 'ar' ? 'ar' : 'en'
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const value = useMemo(() => {
    const t = (path, values) => {
      const current = getValue(translations[language], path)
      const fallback = getValue(translations.en, path)
      const text = current ?? fallback ?? path
      return typeof text === 'string' ? interpolate(text, values) : text
    }

    return {
      language,
      isArabic: language === 'ar',
      setLanguage,
      toggleLanguage: () => setLanguage((previous) => (previous === 'en' ? 'ar' : 'en')),
      t,
    }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
