/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'masariLanguage'

const translations = {
  en: {
    app: {
      language: 'العربية',
      logout: 'Logout',
      brand: 'مساري',
    },
    nav: {
      dashboard: 'Dashboard',
      craftRoadmap: 'Craft your Road Map',
      job: 'Job Details',
      roadmap: 'Roadmap',
      courseAnalysis: 'Course Analysis',
    },
    login: {
      badge: 'Masari Platform',
      heading: 'Welcome back, future-ready student.',
      subtitle:
        'Sign in with your Prince Sattam Bin Abdulaziz University student account.',
      welcomePrompt: 'Welcome to Masari. Your smart path from university courses to real market opportunities starts here.',
      cardTitle: 'Student Login',
      allowedEmail: 'Allowed email format:',
      dummyAccounts: 'Dummy accounts:',
      passwordHint: 'Password:',
      email: 'University Email',
      password: 'Password',
      emailPlaceholder: 'e.g. ahmad.2022@std.psau.edu.sa',
      passwordPlaceholder: 'Enter password',
      login: 'Login',
      signUp: 'Sign Up',
      featureOne: 'PSAU student authentication',
      featureTwo: 'Career dashboard and roadmap',
      requiredError: 'Please enter your university email and password.',
      invalidDomain: 'Use your university email ending with @std.psau.edu.sa to sign in.',
      invalidCredentials: 'Invalid email or password. Try one of the dummy student accounts.',
    },
    dashboard: {
      badge: 'Student Dashboard',
      title: 'Recommended Jobs for Your Major',
      subtitle: 'Welcome {{name}}. Explore careers aligned with your major and current academic profile.',
      welcomeGuest: 'Welcome to Masari',
      guestIntro: 'Start building your personalized career roadmap by answering a few questions about your interests and specialization.',
      guestUser: 'Guest',
      startCrafting: 'Start Crafting Your Roadmap',
      university: 'University',
      college: 'College',
      major: 'Major',
      collegeYear: 'College Year',
      semester: 'Semester',
      studentId: 'Student ID',
      gpa: 'GPA',
      careerGoal: 'Career Goal',
      roadmapCompletion: 'Roadmap Completion in Your Profile',
      roadmapCompletionHint: 'Your checked courses from the roadmap appear here to track real progress over time.',
      completedCoursesList: 'Courses you marked as done',
      completedSearchPlaceholder: 'Search by course name or code',
      noCoursesMatchSearch: 'No completed courses match this search.',
      continueRoadmap: 'Continue this roadmap',
      tabProgress: 'Progress Tracker',
      tabCareers: 'Career Suggestions',
      progressSectionTitle: 'Tracked Completed Courses',
      progressSectionHint: 'Review what you finished in the selected roadmap and continue from where you stopped.',
      noCompletedCoursesYet: 'No courses marked as done yet in this roadmap.',
      unnamedRoadmap: 'Unnamed roadmap',
      roadmapName: 'Roadmap name',
      roadmapMajor: 'Major',
      roadmapLastUpdate: 'Last update',
      noRoadmapProgress: 'No roadmap progress yet',
      overallCompletion: 'Overall completion',
      setDefaultRoadmap: 'Set As Default Roadmap',
      addFavorite: 'Add Roadmap To Favorites',
      removeFavorite: 'Remove from Favorites',
      favoriteRoadmaps: 'Favorite Roadmaps',
      defaultRoadmap: 'Default Roadmap',
      visibility: 'Visibility',
      noFavorites: 'No favorite roadmaps yet',
      careersSectionTitle: 'Recommended Careers',
      careersSectionHint: 'These are suggested target careers for your major. Choose one to open details and generate or continue its roadmap.',
      applicationPriority: 'Application Priority',
      applyCareer: 'Apply for this career',
      noCareers: 'No careers found for this major. Please adjust the dummy profile later if needed.',
    },
    job: {
      notFoundTitle: 'Career Not Found',
      notFoundDesc: 'Please return to the dashboard and select an available career.',
      goDashboard: 'Go to Dashboard',
      badge: 'Job Details',
      yourCollege: 'Your College',
      descriptionTitle: 'Job Description',
      personalizedDesc: 'This recommendation is personalized from your selected college and major to maximize your internship readiness.',
      skillsTitle: 'Required Skills',
      prepareTitle: 'Ready to prepare for this role?',
      prepareDesc: 'Generate a personalized learning roadmap with milestones, courses, and projects tailored to this job opportunity.',
      generateRoadmap: 'Generate Career Roadmap',
    },
    roadmap: {
      title: 'Craft Your Career Roadmap',
      hello: 'Hello {{name}}',
      gpa: 'GPA',
      semester: 'Semester',
      defaultRoadmapSet: 'Default Roadmap (from settings):',
      yes: 'Yes',
      no: 'No',
      yesStartQuiz: 'Yes, start quiz',
      noSkipQuiz: 'No, skip quiz',
      pickField: 'Pick from high-level technology fields.',
      sortCareersBy: 'Sort careers by',
      changeField: 'Change field',
      retakeQuiz: 'Retake quiz',
      sortingMode: 'Sorting mode:',
      sortIndex: 'Index (best fit)',
      sortNearestMajor: 'Nearest to your major',
      sortNearestPref: 'Nearest to your preferences',
      sortDemand: 'Market demand',
      colorScaleExpl: 'Color scale explanation',
      colorScaleDesc: 'Green = most suitable, Red = least suitable (based on current sort).',
      noCareersMatch: 'No careers matched yet. Expand selection or choose a different field/major.',
      cardMajor: 'Major',
      cardCategory: 'Category',
      cardDemand: 'Demand',
      quizTitle: 'Masari: The Tech & Engineering DNA Quiz',
      questionOf: 'Question {{current}} of {{total}}',
      back: 'Back',
      submit: 'Submit',
      next: 'Next',
      closeBtn: '✕ Close',
      hide: 'Hide',
      show: 'Show',
      roadmapForJob: 'roadmap for this job',
      roadmapStepsBased: 'Roadmap Steps (based on {{major}} curriculum)',
      roadmapStepsDesc: 'This is a simplified roadmap for the selected career with gap courses and suggested learning.',
      skillsLabel: 'Skills:',
      targetsJob: 'Targets job',
      foundation: 'Foundation',
      helpsFillGap: '✔ Helps fill gap:',
      careerGoal: 'Career Goal',
      recommendedLearning: 'Recommended learning to close gaps',
      restartJourney: 'Restart Journey',
      unavailableTitle: 'Roadmap Unavailable',
      unavailableDesc: 'Please choose a career from dashboard first to generate a roadmap.',
      guestTitle: 'Build Your Roadmap Without Login',
      guestDesc: 'Choose your major and current level first, then we recommend the closest careers and generate your roadmap instantly.',
      guestProfileTitle: 'Your Profile',
      guestProfileDesc: 'Tell us about yourself to get personalized career recommendations.',
      major: 'Major',
      majorPlaceholder: 'Select your major',
      graduationDate: 'Graduation Date',
      graduationDatePlaceholder: 'Select graduation year',
      currentSemester: 'Current Level',
      currentSemesterPlaceholder: 'Select your current level',
      continueButton: 'Continue',
      askKnownQuestion: 'Do you already know the Field/Job you want to work in?',
      quizOfferText: 'Would you like to have a 5 minute quiz to find suitable careers?',
      fieldQuestion: 'What area of tech do you want to get into?',
      sortingTitle: 'Sort careers by',
      continueToCareers: 'Continue to careers',
      psauCollege: 'College of Engineering and Computer Science - Prince Sattam Bin Abdulaziz University',
      servingCollege: 'Currently serving',
      collegePlaceholder: 'Enter your college name',
      yearLabel: 'Year',
      firstSemester: 'First Semester',
      secondSemester: 'Second Semester',
      showCareers: 'Show Closest Careers',
      closestCareers: 'Closest careers for your major',
      backToStepOne: 'Back to Major and Level',
      leastRequirements: 'Least requirements for entry level',
      majorSkillsForJob: 'Your major skills for this job',
      gapPercentage: 'Gap percentage',
      setDefaultRoadmap: 'Set As Default Roadmap',
      addFavorite: 'Add Roadmap To Favorites',
      removeFavorite: 'Remove from Favorites',
      defaultRoadmap: 'Default Roadmap',
      matched: 'Matched',
      missing: 'Missing',
      favoriteRoadmaps: 'Favorite Roadmaps',
      noFavorites: 'No favorite roadmaps yet',
      selectCareer: 'Select Career Path',
      selectCareerPlaceholder: 'Choose a career role',
      generateGuestRoadmap: 'Generate Roadmap Now',
      guestStudent: 'Guest Student',
      notProvided: 'Not Provided',
      careerRoadmap: 'Career Roadmap',
      roadmapFor: 'Roadmap for {{title}}',
      generatedFrom: 'Generated from your profile: {{major}}{{college}}. Compare each semester course against role requirements and close skill gaps.',
      student: 'Student',
      involvedCourses: 'Involved Courses',
      remainingCourses: 'Remaining Courses',
      current: 'Current',
      completed: 'Completed',
      ongoing: 'Ongoing',
      remaining: 'Remaining',
      matchToJob: 'Match to job requirements',
      detectedGaps: 'Detected Gaps',
      extraResources: 'Extra Resources',
      importantForRole: 'Important for this role',
      importantCoursesFocus: 'Important focus courses',
      progressTitle: 'Your roadmap completion progress',
      progressHint: 'Mark any finished course and your profile completion will update automatically.',
      markAsDone: 'Mark as done',
      viewCourseAnalysis: 'View AI Course Analysis',
      courseAiPanelTitle: 'Interactive Course Intelligence Panel',
      courseAiPanelHint: 'Click any course card in the roadmap timeline to see deeper market analysis and tailored resources.',
      selectCourseHint: 'Select a course from the roadmap above to show AI insights, market need score, and external resources.',
      marketNeedLevel: 'Market need score for this course',
      courseRelationship: 'Linked target role',
      courseDescriptionLabel: 'Course description',
      courseContentSkills: 'Course content and skills',
      matchingMarketSkills: 'Skills aligned with market needs',
      marketGapSkills: 'Gap skills to strengthen',
      requiredSkillsWhyTitle: 'Why these required skills matter',
      requiredSkillsWhyHint: 'Each skill below is requested by the target role. This explanation helps the student understand why extra learning modules are important.',
      skillCovered: 'Covered in this course',
      skillMissing: 'Needs extra learning',
      noDirectMatch: 'No direct market skill match yet for this course.',
      noGapNow: 'Great! No major gap detected for this course now.',
      recommendedExternalResources: 'AI-suggested external resources (articles, videos, courses)',
      closeDetails: 'Close',
      aiModeGap: 'Gap Analysis',
      aiModeFull: 'Full Market-Ready Plan',
      coverageHigh: 'University coverage is strong for this course compared with market needs.',
      coverageMedium: 'University coverage is moderate; a few market topics should be added.',
      coverageLow: 'University coverage is limited for current market demands in this role.',
      aiRecommendationNarrative: 'AI interpretation',
      universityContentLabel: 'The university currently teaches',
      marketMissingLabel: 'Market expects additional focus on',
      addedContentLabel: 'Suggested action: add practical tasks, case-based assignments, and updated market tools for these gaps.',
      fullPlanTitle: 'Comprehensive content plan for market readiness',
      addModulePrefix: 'Add learning module for',
    },
    quiz: {
      q1: 'If you were given a mysterious black box that performs a task, what is your first move?',
      q1a: 'Decorate the box and make the interface easier to use.',
      q1b: 'Open it up to see the circuit boards and microchips inside.',
      q1c: 'Write a script to automate what the box does.',
      q1d: 'Feed it data to see if it can predict the next outcome.',
      q1e: 'Hack into it to see if it\'s vulnerable.',
      q2: 'Which of these sounds like a fun Saturday project?',
      q2a: 'Designing a personal brand logo or a sleek website landing page.',
      q2b: 'Building a smart mirror using a Raspberry Pi and soldering wires.',
      q2c: 'Building a high-performance web server or a mobile app.',
      q2d: 'Creating a bot that identifies objects in your room using a camera.',
      q2e: 'Setting up a home lab with firewalls and secure file storage.',
      q3: 'When a device stops working, what do you suspect first?',
      q3a: 'The user interface is confusing.',
      q3b: 'A physical component burned out.',
      q3c: 'There is a bug in the software logic.',
      q3d: 'The algorithm is biased or lacks enough data.',
      q3e: 'A background process is being throttled or attacked.',
      q4: 'In a Smart City project, which role would you grab?',
      q4a: 'Designing how citizens interact with the city app.',
      q4b: 'Designing sensors and controllers on streetlights.',
      q4c: 'Writing the backend system connecting services.',
      q4d: 'Analyzing traffic patterns to optimize flow.',
      q4e: 'Ensuring the power grid cannot be remotely shut down.',
      q5: 'Which subject peaks your curiosity?',
      q5a: 'Human-Computer Interaction (HCI).',
      q5b: 'Digital Logic Design and VLSI.',
      q5c: 'Data Structures and Algorithms.',
      q5d: 'Probability and Neural Networks.',
      q5e: 'Network Security and Cryptography.',
      q6: 'What is your favorite level of technology?',
      q6a: 'The Surface: what the user sees and touches.',
      q6b: 'The Metal: physical chips and electrical signals.',
      q6c: 'The Logic: code and instructions.',
      q6d: 'The Brain: patterns and learning.',
      q6e: 'The Shield: walls and permissions.',
      q7: 'If you were at a Hackathon, you\'d spend the most time...',
      q7a: 'Perfecting the CSS and user journey.',
      q7b: 'Debugging a microcontroller or Arduino.',
      q7c: 'Architecting the API and database.',
      q7d: 'Training a model on a large dataset.',
      q7e: 'Stress-testing the system for leaks.',
      q8: 'Pick a tool that sounds interesting:',
      q8a: 'Figma or Adobe XD.',
      q8b: 'Oscilloscope or Multimeter.',
      q8c: 'VS Code or IntelliJ.',
      q8d: 'Jupyter Notebook or PyTorch.',
      q8e: 'Wireshark or Kali Linux.',
      q9: 'What does Efficiency mean to you?',
      q9a: 'Reducing the number of clicks a user makes.',
      q9b: 'Reducing power consumption and heat in a chip.',
      q9c: 'Making code run in O(n log n) instead of O(n^2).',
      q9d: 'Increasing prediction accuracy from 85% to 95%.',
      q9e: 'Reducing the attack surface of a network.',
      q10: 'When you hear Apple, what do you think of?',
      q10a: 'Beautiful, minimalist design.',
      q10b: 'Incredible chip architecture.',
      q10c: 'Seamless app ecosystem.',
      q10d: 'FaceID and Siri intelligence.',
      q10e: 'End-to-end encryption security.',
      q11: 'Do you prefer working with things you can...',
      q11a: 'Visualize.',
      q11b: 'Touch.',
      q11c: 'Build.',
      q11d: 'Analyze.',
      q11e: 'Protect.',
      q12: 'Which Problem irritates you the most?',
      q12a: 'Ugly responsive website.',
      q12b: 'Remote control battery drain.',
      q12c: 'App crashes under load.',
      q12d: 'Bad recommendation engine.',
      q12e: 'Password leak notification.',
      q13: 'In a car, you are most interested in:',
      q13a: 'Dashboard display and comfort.',
      q13b: 'ECU and hardware sensors.',
      q13c: 'Infotainment software and navigation.',
      q13d: 'Self-driving features and lane detection.',
      q13e: 'Security of keyless entry system.',
      q14: 'What is your ideal work environment?',
      q14a: 'Creative agency with whiteboards.',
      q14b: 'Lab with hardware kits and soldering.',
      q14c: 'High-growth startup building big products.',
      q14d: 'Research center for new insights.',
      q14e: 'Security operations center.',
      q15: 'If you were learning a new language, you\'d pick:',
      q15a: 'CSS/Swift (UI).',
      q15b: 'Verilog/Assembly (Hardware).',
      q15c: 'Java/Go (Backend/Systems).',
      q15d: 'Python/R (Data/AI).',
      q15e: 'C/Bash (Security/Scripting).',
      q16: 'How do you feel about Complexity?',
      q16a: 'Hide it from users.',
      q16b: 'Fit more transistors in small space.',
      q16c: 'Manage modules communication.',
      q16d: 'Find signal in the noise.',
      q16e: 'Find vulnerabilities to shore up.',
      q17: 'Which Magic trick is coolest?',
      q17a: 'Dark mode switch.',
      q17b: 'Tiny chip billions calc/s.',
      q17c: 'Deploy code to 1M users.',
      q17d: 'Computer writes poems.',
      q17e: 'Sending unbreakable secret message.',
      q18: 'Your favorite Optimization is:',
      q18a: 'Aesthetic/usability.',
      q18b: 'Clock speed/thermal.',
      q18c: 'Scalability/memory.',
      q18d: 'Model weight/hyperparams.',
      q18e: 'Firewall/permission.',
      q19: 'What kind of Legacy do you want?',
      q19a: 'Made tech feel human.',
      q19b: 'Built hardware era.',
      q19c: 'Built platforms world runs on.',
      q19d: 'Solved complex data problems.',
      q19e: 'Kept digital life safe.',
      q20: 'Finish: The best part of tech is...',
      q20a: 'How it looks and feels.',
      q20b: 'Physics and engineering.',
      q20c: 'Logic and code power.',
      q20d: 'Intelligence and possibilities.',
      q20e: 'Privacy and resilience.',
    },
    courseAnalysis: {
      badge: 'Masari Course Analysis',
      title: 'Compare Courses with Job Skill Requirements',
      subtitle: 'Understand how your university courses align with real industry roles, identify skill gaps, and follow recommended learning resources.',
      searchPlaceholder: 'Search by course name or code',
      majorFilter: 'Major',
      semesterFilter: 'Semester',
      allSemesters: 'All Semesters',
      marketRequirementsTitle: 'Saudi Market Requirements',
      companiesContributing: 'Companies contributing requirements',
      currentSemester: 'Current Semester',
      activeRequirements: 'Active Requirements',
      requirementWindow: 'Semester Window',
      companyWeight: 'Company Weight',
      role: 'Target Role',
      demandSkills: 'Demanded Skills',
      details: 'Details',
      companiesSuggesting: 'Companies Suggesting This Course',
      noCompanyMatches: 'No matching companies for this course at the current level.',
      totalCourses: 'Total Courses',
      averageMatch: 'Average Match',
      topCompanies: 'Top Market Companies',
      sortHigh: 'Sort: Match High to Low',
      sortLow: 'Sort: Match Low to High',
      sortAZ: 'Sort: Course A-Z',
      sortSemester: 'Sort: Semester Asc',
      track: 'Track',
      matchingPercentage: 'Matching Percentage',
      skillsGained: 'Skills Gained',
      missingSkills: 'Missing Skills',
      suggestedResources: 'Suggested Learning Resources',
      closeDetails: 'Close Details',
      noCourses: 'No courses found for the selected filter.',
      all: 'All',
    },
    landing: {
      demo: 'Request Demo',
      badge: 'PSAU Career Platform',
      title: 'Masari Platform for PSAU Students',
      subtitle: 'A smart guide for students of the College of Engineering and Computer Science to connect major courses with market-ready careers.',
      introMessage: 'Welcome to Masari. This platform currently serves PSAU students in Software Engineering, Computer Science, Information Systems, and Computer Engineering.',
      welcomeHeadline: 'Welcome to Masari - Official platform for PSAU Engineering and Computer Science students',
      welcomeSubline: 'Choose your major, select your level, discover the closest careers, and get a focused roadmap with key courses and market gap resources.',
      welcomeLineOne: 'Start with your major and academic level to get personalized role matching.',
      welcomeLineTwo: 'Track important courses, close market gaps, and build your roadmap semester by semester.',
      statMajors: 'Supported Majors',
      statCareers: 'Suggested Career Paths',
      statRoadmap: 'Personalized Roadmap',
      primary: 'Start Building My Roadmap',
      secondary: 'Sign In as Student',
      signInTop: 'Sign In',
      signInBest: 'Sign In To Get The Best Results!',
      semester: 'This Semester',
      course: 'Data Structures and Algorithms',
      suggestedRole: 'Suggested role',
      role: 'Backend Engineer Intern',
      gapTitle: 'Skill gap to close',
      gap: 'API design and system thinking',
      why: 'Why Students Choose Masari',
      featureOneTitle: 'Course-to-Job Mapping',
      featureOneDesc: 'Instantly see which careers align with your current subjects and degree pathway.',
      featureTwoTitle: 'Personalized Skill Plan',
      featureTwoDesc: 'AI recommends projects, certifications, and electives to close skill gaps before graduation.',
      featureThreeTitle: 'Opportunity Matching',
      featureThreeDesc: 'Discover internships and entry roles that match your coursework, interests, and progress level.',
      ctaTitle: 'Build your future while you study.',
      ctaDesc: 'Join Masari and get AI-powered career guidance that evolves with every semester.',
      quizSummaryTitle: 'Assessment Results',
      quizSummaryDesc: 'Top recommended fields and careers based on your quiz answers.',
      topFields: 'Top 3 recommended fields',
      topJobs: 'Top 10 recommended jobs',
      noTopFields: 'No fields to display yet.',
      noTopJobs: 'No jobs to display yet.',
      ctaButton: 'Join Masari Free',
      footerOne: '2026 Masari Platform. Built for ambitious students.',
      footerTwo: 'Connect courses, skills, and career opportunities in one place.',
    },
  },
  ar: {
    app: {
      language: 'English',
      logout: 'تسجيل الخروج',
      brand: 'مساري',
    },
    nav: {
      dashboard: 'لوحة التحكم',
      craftRoadmap: 'اصنع خارطتك المهنية',
      job: 'تفاصيل الوظيفة',
      roadmap: 'الخريطة المهنية',
      courseAnalysis: 'تحليل المقررات',
    },
    login: {
      badge: 'منصة مساري',
      heading: 'مرحباً بعودتك، أيها الطالب المستعد للمستقبل.',
      subtitle: 'سجّل الدخول باستخدام حسابك الطلابي في جامعة الأمير سطام بن عبدالعزيز.',
      welcomePrompt: 'مرحباً بك في مساري. طريقك الذكي من مقررات الجامعة إلى فرص سوق العمل يبدأ من هنا.',
      cardTitle: 'دخول الطالب',
      allowedEmail: 'صيغة البريد المسموحة:',
      dummyAccounts: 'الحسابات التجريبية:',
      passwordHint: 'كلمة المرور:',
      email: 'البريد الجامعي',
      password: 'كلمة المرور',
      emailPlaceholder: 'مثال: ahmad.2022@std.psau.edu.sa',
      passwordPlaceholder: 'أدخل كلمة المرور',
      login: 'تسجيل الدخول',
      signUp: 'إنشاء حساب',
      featureOne: 'توثيق طلاب جامعة الأمير سطام',
      featureTwo: 'لوحة مهنية وخارطة طريق',
      requiredError: 'يرجى إدخال البريد الجامعي وكلمة المرور.',
      invalidDomain: 'يجب استخدام بريد الجامعة المنتهي بـ @std.psau.edu.sa.',
      invalidCredentials: 'البريد أو كلمة المرور غير صحيحة. جرّب أحد الحسابات التجريبية.',
    },
    dashboard: {
      badge: 'لوحة الطالب',
      title: 'الوظائف المناسبة لتخصصك',
      subtitle: 'مرحباً {{name}}. استكشف الوظائف المتوافقة مع تخصصك وملفك الأكاديمي الحالي.',
      welcomeGuest: 'مرحباً بك في مساري',
      guestIntro: 'ابدأ ببناء خريطتك المهنية الشخصية عن طريق الإجابة على عدة أسئلة عن اهتماماتك وتخصصك.',
      guestUser: 'زائر',
      startCrafting: 'ابدأ بناء خريطتك المهنية',
      university: 'الجامعة',
      college: 'الكلية',
      major: 'التخصص',
      collegeYear: 'السنة الدراسية',
      semester: 'الفصل الدراسي',
      studentId: 'الرقم الجامعي',
      gpa: 'المعدل',
      careerGoal: 'الهدف المهني',
      roadmapCompletion: 'نسبة إكمال الخريطة في ملفك',
      roadmapCompletionHint: 'أي مقرر تضع عليه علامة صح في الخريطة سيظهر هنا لمتابعة تقدمك الفعلي.',
      completedCoursesList: 'المقررات التي أنهيتها',
      completedSearchPlaceholder: 'ابحث باسم المقرر أو رمزه',
      noCoursesMatchSearch: 'لا توجد مقررات مكتملة مطابقة لنتيجة البحث.',
      continueRoadmap: 'متابعة هذه الخريطة',
      tabProgress: 'متابعة التقدم',
      tabCareers: 'الوظائف المقترحة',
      progressSectionTitle: 'المقررات المكتملة في الخريطة',
      progressSectionHint: 'راجع ما أنهيته في الخريطة المختارة وكمل من آخر نقطة وصلت لها.',
      noCompletedCoursesYet: 'لم يتم تحديد أي مقرر كمكتمل في هذه الخريطة بعد.',
      unnamedRoadmap: 'خريطة بدون اسم',
      roadmapName: 'اسم الخريطة',
      roadmapMajor: 'التخصص',
      roadmapLastUpdate: 'آخر تحديث',
      noRoadmapProgress: 'لا يوجد تقدم مسجل في الخريطة بعد',
      overallCompletion: 'الإكمال الكلي',
      setDefaultRoadmap: 'تعيين كخريطة افتراضية',
      addFavorite: 'أضف الخريطة للمفضلة',
      removeFavorite: 'إزالة من المفضلة',
      favoriteRoadmaps: 'الخرائط المفضلة',
      defaultRoadmap: 'الخريطة الافتراضية',
      noFavorites: 'لا توجد خرائط مفضلة بعد',
      careersSectionTitle: 'المسارات المهنية المقترحة',
      careersSectionHint: 'هذه مسارات وظيفية مقترحة حسب تخصصك. اختر أي مسار لعرض التفاصيل وإنشاء الخريطة أو استكمالها.',
      applicationPriority: 'أولوية التقديم',
      applyCareer: 'التقديم على هذا المسار',
      noCareers: 'لا توجد وظائف مطابقة لهذا التخصص حالياً. يمكنك تعديل البيانات التجريبية لاحقاً.',
    },
    job: {
      notFoundTitle: 'الوظيفة غير موجودة',
      notFoundDesc: 'يرجى العودة إلى لوحة التحكم واختيار وظيفة متاحة.',
      goDashboard: 'العودة إلى اللوحة',
      badge: 'تفاصيل الوظيفة',
      yourCollege: 'كليتك',
      descriptionTitle: 'وصف الوظيفة',
      personalizedDesc: 'تم تخصيص هذا الترشيح بناءً على كليتك وتخصصك لزيادة جاهزيتك للتدريب والعمل.',
      skillsTitle: 'المهارات المطلوبة',
      prepareTitle: 'هل أنت مستعد للاستعداد لهذه الوظيفة؟',
      prepareDesc: 'أنشئ خارطة طريق تعليمية مخصصة تتضمن مراحل ومقررات ومشاريع ملائمة لهذه الفرصة.',
      generateRoadmap: 'إنشاء الخريطة المهنية',
    },
    roadmap: {
      title: 'بناء خريطتك المهنية',
      hello: 'أهلاً {{name}}',
      gpa: 'المعدل',
      semester: 'الفصل الدراسي',
      defaultRoadmapSet: 'الخريطة الافتراضية (من الإعدادات):',
      yes: 'نعم',
      no: 'لا',
      yesStartQuiz: 'نعم، ابدأ الاختبار',
      noSkipQuiz: 'لا، تخطى الاختبار',
      pickField: 'اختر من المجالات التقنية العامة.',
      sortCareersBy: 'ترتيب الوظائف حسب',
      changeField: 'تغيير المجال',
      retakeQuiz: 'إعادة الاختبار',
      sortingMode: 'طريقة الترتيب:',
      sortIndex: 'المؤشر (أفضل توافق)',
      sortNearestMajor: 'الأقرب لتخصصك',
      sortNearestPref: 'الأقرب لاهتماماتك',
      sortDemand: 'طلب السوق',
      colorScaleExpl: 'شرح مقياس الألوان',
      colorScaleDesc: 'الأخضر = الأنسب، الأحمر = الأقل مناسبة (بناءً على الترتيب الحالي).',
      noCareersMatch: 'لا توجد وظائف مطابقة حتى الآن. وسّع التحديد أو اختر مجالاً/تخصصاً آخر.',
      cardMajor: 'التخصص',
      cardCategory: 'المجال',
      cardDemand: 'الطلب',
      quizTitle: 'مساري: اختبار الاهتمامات التقنية والهندسية',
      questionOf: 'سؤال {{current}} من {{total}}',
      back: 'رجوع',
      submit: 'إرسال',
      next: 'التالي',
      closeBtn: '✕ إغلاق',
      hide: 'إخفاء',
      show: 'عرض',
      roadmapForJob: 'خريطة هذه الوظيفة',
      roadmapStepsBased: 'خطوات الخريطة (بناءً على خطة {{major}})',
      roadmapStepsDesc: 'هذه خريطة مبسطة للمسار المختار مع توضيح المقررات ومصادر التعلم المقترحة.',
      skillsLabel: 'المهارات:',
      targetsJob: 'تستهدف الوظيفة',
      foundation: 'تأسيسي',
      helpsFillGap: '✔ تساعد في سد الفجوة:',
      careerGoal: 'الهدف المهني',
      recommendedLearning: 'مصادر التعلم المقترحة لسد الفجوات',
      restartJourney: 'بدء الرحلة من جديد',
      unavailableTitle: 'الخريطة غير متاحة',
      unavailableDesc: 'يرجى اختيار وظيفة من لوحة التحكم أولاً لإنشاء الخريطة.',
      guestTitle: 'أنشئ خريطتك المهنية بدون تسجيل دخول',
      guestDesc: 'اختر تخصصك ومستواك الدراسي أولاً، ثم ستظهر لك الوظائف الأقرب لتخصصك وبعدها ننشئ لك خريطة مهنية مباشرة.',
      guestProfileTitle: 'ملفك الشخصي',
      guestProfileDesc: 'خبرنا عن نفسك لكي نقدم لك توصيات وظيفية مخصصة.',
      major: 'التخصص',
      majorPlaceholder: 'اختر تخصصك',
      graduationDate: 'تاريخ التخرج',
      graduationDatePlaceholder: 'اختر سنة التخرج',
      currentSemester: 'المستوى الحالي',
      currentSemesterPlaceholder: 'اختر مستواك الحالي',
      continueButton: 'المتابعة',
      askKnownQuestion: 'هل تعرف بالفعل المجال/الوظيفة التي تريد العمل فيها؟',
      quizOfferText: 'هل ترغب في اختبار مدته 5 دقائق لتحديد الوظائف المناسبةً لك؟',
      fieldQuestion: 'ما مجال التكنولوجيا الذي تود الالتحاق به؟',
      sortingTitle: 'رتب الوظائف حسب',
      continueToCareers: 'المتابعة إلى الوظائف',
      psauCollege: 'كلية الهندسة وعلوم الحاسب - جامعة الأمير سطام بن عبدالعزيز',
      servingCollege: 'الخدمة الحالية',
      collegePlaceholder: 'اكتب اسم الكلية',
      yearLabel: 'السنة',
      firstSemester: 'الفصل الأول',
      secondSemester: 'الفصل الثاني',
      showCareers: 'إظهار الوظائف الأقرب',
      closestCareers: 'الوظائف الأقرب لتخصصك',
      backToStepOne: 'الرجوع لاختيار التخصص والمستوى',
      selectCareer: 'اختر المسار الوظيفي',
      selectCareerPlaceholder: 'اختر وظيفة مناسبة',
      leastRequirements: 'أقل متطلبات للدخول',
      majorSkillsForJob: 'مهارات تخصصك لهذه الوظيفة',
      gapPercentage: 'نسبة الفجوة',
      setDefaultRoadmap: 'تعيين كخريطة افتراضية',
      addFavorite: 'أضف الخريطة للمفضلة',
      removeFavorite: 'إزالة من المفضلة',
      defaultRoadmap: 'الخريطة الافتراضية',
      favoriteRoadmaps: 'الخرائط المفضلة',
      noFavorites: 'لا توجد خرائط مفضلة بعد',
      generateGuestRoadmap: 'إنشاء الخريطة الآن',
      guestStudent: 'طالب زائر',
      notProvided: 'غير محدد',
      careerRoadmap: 'الخريطة المهنية',
      matched: 'المطابقة',
      missing: 'المفقود',
      roadmapFor: 'الخريطة المهنية لـ {{title}}',
      generatedFrom: 'تم الإنشاء بناءً على ملفك: {{major}}{{college}}. قارن كل مقرر بمتطلبات الوظيفة وأغلق فجوات المهارات.',
      student: 'الطالب',
      involvedCourses: 'المقررات التي درسها',
      remainingCourses: 'المقررات المتبقية',
      current: 'الحالي',
      completed: 'مكتمل',
      ongoing: 'جاري',
      remaining: 'متبقي',
      matchToJob: 'نسبة التطابق مع الوظيفة',
      detectedGaps: 'الفجوات المكتشفة',
      extraResources: 'موارد إضافية',
      importantForRole: 'مقرر مهم لهذه الوظيفة',
      importantCoursesFocus: 'عدد المقررات المهمة التي يجب التركيز عليها',
      progressTitle: 'نسبة إكمالك للخريطة المهنية',
      progressHint: 'ضع علامة صح على أي مقرر أنهيته وسيتم تحديث النسبة في ملفك تلقائياً.',
      markAsDone: 'تحديد كمكتمل',
      viewCourseAnalysis: 'عرض تحليل المقرر بالذكاء الاصطناعي',
      courseAiPanelTitle: 'لوحة تحليل المقرر التفاعلية',
      courseAiPanelHint: 'اضغط على أي مقرر في الخريطة لعرض تحليل أعمق لاحتياج السوق والموارد المناسبة.',
      selectCourseHint: 'اختر مقررًا من الخريطة بالأعلى ليظهر تحليل الذكاء الاصطناعي ونسبة احتياج السوق والموارد الخارجية.',
      marketNeedLevel: 'نسبة احتياج سوق العمل لهذا المقرر',
      courseRelationship: 'الوظيفة المرتبطة',
      courseDescriptionLabel: 'وصف المقرر',
      courseContentSkills: 'محتوى المقرر والمهارات',
      matchingMarketSkills: 'المهارات المتوافقة مع احتياج السوق',
      marketGapSkills: 'المهارات المطلوب تقويتها لسد الفجوة',
      requiredSkillsWhyTitle: 'لماذا هذه المهارات المطلوبة مهمة؟',
      requiredSkillsWhyHint: 'كل مهارة بالأسفل مطلوبة من الوظيفة المستهدفة، والشرح يساعد الطالب على فهم سبب الحاجة للمهارات الإضافية.',
      skillCovered: 'مغطاة في هذا المقرر',
      skillMissing: 'تحتاج تعلم إضافي',
      noDirectMatch: 'لا يوجد تطابق مباشر قوي مع مهارات السوق لهذا المقرر حالياً.',
      noGapNow: 'ممتاز! لا توجد فجوة كبيرة حالياً في هذا المقرر.',
      recommendedExternalResources: 'موارد خارجية مقترحة بالذكاء الاصطناعي (مقالات، فيديوهات، كورسات)',
      closeDetails: 'إغلاق',
      aiModeGap: 'تحليل الفجوة',
      aiModeFull: 'خطة شاملة جاهزة لسوق العمل',
      coverageHigh: 'تغطية الجامعة قوية في هذا المقرر مقارنة باحتياج السوق.',
      coverageMedium: 'تغطية الجامعة متوسطة، وهناك موضوعات سوقية تحتاج إضافة.',
      coverageLow: 'تغطية الجامعة محدودة أمام احتياج السوق الحالي لهذه الوظيفة.',
      aiRecommendationNarrative: 'تفسير الذكاء الاصطناعي',
      universityContentLabel: 'الجامعة تدرّس حالياً',
      marketMissingLabel: 'سوق العمل يحتاج تركيزاً إضافياً على',
      addedContentLabel: 'الإضافة المقترحة: مهام عملية، وحالات تطبيقية، وأدوات سوق حديثة لتغطية هذه الفجوات.',
      fullPlanTitle: 'خطة محتوى شاملة لتجهيزك لسوق العمل',
      addModulePrefix: 'إضافة وحدة تعلم خاصة بـ',
    },
    quiz: {
      q1: 'إذا تم إعطاؤك صندوق أسود غامض يقوم بمهمة ما، ماذا ستفعل أولاً؟',
      q1a: 'تزيينها وجعل الواجهة أسهل في الاستخدام.',
      q1b: 'فتحها لرؤية لوحات الدوائر والرقائق الدقيقة بالداخل.',
      q1c: 'كتابة سكريبت لأتمتة ما يفعله الصندوق.',
      q1d: 'إدخال بيانات لمعرفة ما إذا كان يستطيع التنبؤ بالمخرجات.',
      q1e: 'اختراقها لمعرفة ما إذا كانت عرضة للثغرات الأمنية.',
      q2: 'أي من هذه يبدو مشروعاً ممتعاً ليوم السبت؟',
      q2a: 'تصميم شعار علامتك الشخصية أو صفحة هبوط موقع أنيقة.',
      q2b: 'بناء مرآة ذكية باستخدام Raspberry Pi وتلحيم الأسلاك.',
      q2c: 'بناء خادم ويب عالي الأداء أو تطبيق محمول.',
      q2d: 'إنشاء روبوت يعرّف الأشياء في غرفتك باستخدام الكاميرا.',
      q2e: 'إعداد مختبر منزلي به جدران حماية (Firewalls) وتخزين ملفات آمن.',
      q3: 'عندما يتوقف جهاز عن العمل، ماذا تشك أولاً؟',
      q3a: 'واجهة المستخدم غير واضحة.',
      q3b: 'مكون فيزيائي احترق.',
      q3c: 'يوجد خطأ في منطق البرمجية.',
      q3d: 'الخوارزمية متحيزة أو تفتقر لبيانات كافية.',
      q3e: 'عملية خفية يتم إيقافها أو يتعرض لهجوم.',
      q4: 'في مشروع مدينة ذكية، أي دور تختار؟',
      q4a: 'تصميم كيفية تفاعل المواطنين مع تطبيق المدينة.',
      q4b: 'تصميم أجهزة استشعار وحدات تحكم على أضواء الشوارع.',
      q4c: 'كتابة نظام الخادم الذي يربط الخدمات.',
      q4d: 'تحليل أنماط المرور لتحسين التدفق.',
      q4e: 'ضمان عدم إمكانية إيقاف الشبكة الكهربائية عن بُعد.',
      q5: 'أي موضوع يثير فضولك؟',
      q5a: 'التفاعل بين الإنسان والحاسب (HCI).',
      q5b: 'تصميم المنطق الرقمي ودوائر VLSI.',
      q5c: 'هياكل البيانات والخوارزميات.',
      q5d: 'الاحتمالات والشبكات العصبية.',
      q5e: 'أمان الشبكات والتشفير.',
      q6: 'ما المستوى التقني المفضل لك؟',
      q6a: 'السطح: ما يراه ويلمسه المستخدم.',
      q6b: 'العتاد: الرقائق الفيزيائية والإشارات الكهربائية.',
      q6c: 'المنطق: الكود والتعليمات.',
      q6d: 'الدماغ: الأنماط والتعلم.',
      q6e: 'الدرع: الجدران والأذونات.',
      q7: 'إذا كنت في مسابقة برمجية، ستقضي معظم الوقت...',
      q7a: 'في إتقان CSS ورحلة المستخدم.',
      q7b: 'في تصحيح أخطاء جهاز تحكم دقيق أو Arduino.',
      q7c: 'في معمارية الـ API وقاعدة البيانات.',
      q7d: 'في تدريب نموذج على مجموعة بيانات كبيرة.',
      q7e: 'في اختبار الأمان وفحص الثغرات.',
      q8: 'اختر أداة تبدو مثيرة للاهتمام:',
      q8a: 'Figma أو Adobe XD.',
      q8b: 'جهاز قياس الذبذبات (Oscilloscope) أو جهاز قياس التيار.',
      q8c: 'VS Code أو IntelliJ.',
      q8d: 'Jupyter Notebook أو PyTorch.',
      q8e: 'Wireshark أو Kali Linux.',
      q9: 'ماذا تعني الكفاءة بالنسبة لك؟',
      q9a: 'تقليل عدد النقرات التي يقوم بها المستخدم.',
      q9b: 'تقليل استهلاك الطاقة والحرارة في الرقاقة.',
      q9c: 'جعل الكود يعمل بـ O(n log n) بدلاً من O(n^2).',
      q9d: 'زيادة دقة التنبؤ من 85% إلى 95%.',
      q9e: 'تقليل نقاط ضعف الأمان في الشبكة.',
      q10: 'عندما تسمع كلمة Apple، بماذا تفكر؟',
      q10a: 'تصميم رائع وبسيط.',
      q10b: 'معمارية رقاقات لا تصدق.',
      q10c: 'نظام تطبيقات متكامل بسلاسة.',
      q10d: 'ذكاء FaceID و Siri.',
      q10e: 'التشفير من طرف لطرف.',
      q11: 'هل تفضل العمل مع أشياء يمكنك...',
      q11a: 'تصورها.',
      q11b: 'لمسها.',
      q11c: 'بناؤها.',
      q11d: 'تحليلها.',
      q11e: 'حمايتها.',
      q12: 'أي مشكلة تزعجك أكثر؟',
      q12a: 'موقع ويب قبيح وغير متجاوب.',
      q12b: 'بطارية جهاز تحكم تنفد بسرعة.',
      q12c: 'تطبيق ينهار تحت الحمل.',
      q12d: 'محرك توصيات سيئ.',
      q12e: 'تنبيه تسرب كلمة المرور.',
      q13: 'في السيارة، أنت مهتم بـ:',
      q13a: 'لوحة المعلومات والراحة.',
      q13b: 'وحدة التحكم بالمحرك وأجهزة الاستشعار.',
      q13c: 'برامج الترفيه والملاحة.',
      q13d: 'ميزات القيادة الذاتية والكشف عن المسارات.',
      q13e: 'أمان نظام المفاتيح اللاسلكية.',
      q14: 'ما بيئة العمل المثالية لك؟',
      q14a: 'وكالة إبداعية بها لوحات رسم.',
      q14b: 'مختبر بأدوات عتاد وأجهزة لحام.',
      q14c: 'شركة ناشئة سريعة النمو تبني منتجات ضخمة.',
      q14d: 'مركز أبحاث للرؤى والاكتشافات الجديدة.',
      q14e: 'مركز عمليات الأمان.',
      q15: 'إذا كنت تتعلم لغة برمجية جديدة، ستختار:',
      q15a: 'CSS/Swift (واجهة المستخدم).',
      q15b: 'Verilog/Assembly (العتاد).',
      q15c: 'Java/Go (الأنظمة الخلفية والأنظمة).',
      q15d: 'Python/R (البيانات والذكاء الاصطناعي).',
      q15e: 'C/Bash (الأمان والبرامج النصية).',
      q16: 'كيف تشعر تجاه التعقيد؟',
      q16a: 'إخفاؤها عن المستخدم.',
      q16b: 'وضع مزيد من المواصلات في مساحة صغيرة.',
      q16c: 'إدارة اتصالات الوحدات.',
      q16d: 'إيجاد الإشارة في الضوضاء.',
      q16e: 'البحث عن الثغرات الأمنية لتعزيز الدفاع.',
      q17: 'أي حيلة سحرية الأكثر روعة؟',
      q17a: 'مفتاح الوضع الليلي.',
      q17b: 'رقاقة صغيرة تعمل مليارات العمليات/ثانية.',
      q17c: 'نشر الكود إلى مليون مستخدم.',
      q17d: 'الحاسب يكتب قصائد.',
      q17e: 'إرسال رسالة سرية غير قابلة للكسر.',
      q18: 'تحسينك المفضل هو:',
      q18a: 'الجماليات والقابلية للاستخدام.',
      q18b: 'سرعة الساعة والحرارة.',
      q18c: 'القابلية للتوسع والذاكرة.',
      q18d: 'وزن النموذج والمعاملات الفائقة.',
      q18e: 'جدار الحماية والأذونات.',
      q19: 'أي نوع من التراث تريد تحقيقه؟',
      q19a: 'جعلت التكنولوجيا إنسانية.',
      q19b: 'بنيت عصر العتاد.',
      q19c: 'بنيت منصات يعتمد عليها العالم.',
      q19d: 'حللت مشاكل البيانات المعقدة.',
      q19e: 'حافظت على الحياة الرقمية آمنة.',
      q20: 'أكمل: أفضل جزء في التكنولوجيا هو...',
      q20a: 'كيف تبدو وتشعر.',
      q20b: 'الفيزياء والهندسة.',
      q20c: 'قوة المنطق والكود.',
      q20d: 'الذكاء والإمكانيات.',
      q20e: 'الخصوصية والمتانة.',
    },
    courseAnalysis: {
      badge: 'تحليل مقررات مساري',
      title: 'قارن المقررات مع متطلبات الوظائف',
      subtitle: 'افهم كيف تتوافق مقرراتك الجامعية مع الأدوار المهنية الحقيقية وحدد فجوات المهارات واتبع الموارد المقترحة.',
      searchPlaceholder: 'ابحث باسم المقرر أو رمزه',
      majorFilter: 'التخصص',
      semesterFilter: 'الفصل',
      allSemesters: 'كل الفصول',
      marketRequirementsTitle: 'متطلبات سوق العمل السعودي',
      companiesContributing: 'الشركات التي وضعت هذه المتطلبات',
      currentSemester: 'الفصل الحالي',
      activeRequirements: 'المتطلبات النشطة',
      requirementWindow: 'نطاق الفصول',
      companyWeight: 'وزن الشركة',
      role: 'الدور الوظيفي المستهدف',
      demandSkills: 'المهارات المطلوبة',
      details: 'التفاصيل',
      companiesSuggesting: 'الشركات التي تقترح هذا المقرر',
      noCompanyMatches: 'لا توجد شركات مطابقة لهذا المقرر في المستوى الحالي.',
      totalCourses: 'إجمالي المقررات',
      averageMatch: 'متوسط التطابق',
      topCompanies: 'أبرز شركات السوق',
      sortHigh: 'الترتيب: أعلى تطابق إلى أقل',
      sortLow: 'الترتيب: أقل تطابق إلى أعلى',
      sortAZ: 'الترتيب: المقررات أبجدياً',
      sortSemester: 'الترتيب: حسب الفصل تصاعدياً',
      track: 'المسار',
      matchingPercentage: 'نسبة التطابق',
      skillsGained: 'المهارات المكتسبة',
      missingSkills: 'المهارات الناقصة',
      suggestedResources: 'الموارد التعليمية المقترحة',
      closeDetails: 'إغلاق التفاصيل',
      noCourses: 'لا توجد مقررات مطابقة للفلترة المحددة.',
      all: 'الكل',
    },
    landing: {
      demo: 'اطلب عرضاً تجريبياً',
      badge: 'منصة مساري لجامعة الأمير سطام',
      title: 'منصة مساري لطلاب جامعة الأمير سطام',
      subtitle: 'منصة ذكية تساعد طلاب كلية الهندسة وعلوم الحاسب على ربط المقررات بالوظائف الأقرب لسوق العمل.',
      introMessage: 'مرحباً بك في مساري. المنصة حالياً تخدم طلاب تخصصات: هندسة البرمجيات، علوم الحاسب، نظم المعلومات، وهندسة الحاسب.',
      welcomeHeadline: 'مرحباً بك في مساري - المنصة الرسمية لطلاب كلية الهندسة وعلوم الحاسب بجامعة الأمير سطام',
      welcomeSubline: 'اختر تخصصك، حدد مستواك، اكتشف الوظائف الأقرب، واحصل على خريطة مركزة بالمقررات المهمة وموارد سد فجوات السوق.',
      welcomeLineOne: 'ابدأ باختيار تخصصك ومستواك الدراسي لتحصل على وظائف مقترحة بشكل مخصص.',
      welcomeLineTwo: 'تابع المقررات المهمة، وأغلق فجوات السوق، وابنِ خريطتك المهنية فصلًا بعد فصل.',
      statMajors: 'التخصصات المدعومة',
      statCareers: 'المسارات الوظيفية المقترحة',
      statRoadmap: 'خريطة مهنية مخصصة',
      primary: 'ابدأ بناء الخريطة المهنية',
      secondary: 'تسجيل دخول الطالب',
      signInTop: 'تسجيل الدخول',
      signInBest: 'سجّل الدخول لتحصل على أفضل نتائج!',
      semester: 'هذا الفصل',
      course: 'هياكل البيانات والخوارزميات',
      suggestedRole: 'الوظيفة المقترحة',
      role: 'متدرب مهندس برمجيات خلفية',
      gapTitle: 'فجوة مهارية تحتاج إغلاقها',
      gap: 'تصميم الواجهات البرمجية والتفكير المنظومي',
      why: 'لماذا يختار الطلاب منصة مساري',
      featureOneTitle: 'ربط المقررات بالوظائف',
      featureOneDesc: 'اعرف فوراً الوظائف التي تتوافق مع مقرراتك الحالية وخطتك الدراسية.',
      featureTwoTitle: 'خطة مهارية مخصصة',
      featureTwoDesc: 'يقترح الذكاء الاصطناعي مشاريع وشهادات ومقررات اختيارية لسد الفجوات قبل التخرج.',
      featureThreeTitle: 'مطابقة الفرص',
      featureThreeDesc: 'اكتشف التدريبات والوظائف المبتدئة المناسبة لمقرراتك واهتماماتك ومستواك الحالي.',
      ctaTitle: 'ابنِ مستقبلك أثناء الدراسة.',
      ctaDesc: 'انضم إلى مساري واحصل على إرشاد مهني ذكي يتطور مع كل فصل دراسي.',
      quizSummaryTitle: 'نتائج الاختبار',
      quizSummaryDesc: 'أفضل التخصصات والوظائف الموصى بها بناءً على إجابات الاختبار.',
      topFields: 'أفضل 3 تخصصات مقترحة',
      topJobs: 'أفضل 10 وظائف مقترحة',
      noTopFields: 'لا توجد تخصصات للعرض حالياً.',
      noTopJobs: 'لا توجد وظائف للعرض حالياً.',
      ctaButton: 'انضم إلى مساري مجاناً',
      footerOne: 'منصة مساري 2026. صممت للطلاب الطموحين.',
      footerTwo: 'اربط بين المقررات والمهارات والفرص المهنية في مكان واحد.',
    },
  },
}

const LanguageContext = createContext(null)

function getValue(object, path) {
  return path.split('.').reduce((current, key) => current?.[key], object)
}

function interpolate(text, values = {}) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replace(new RegExp(`{{${key}}}`, 'g'), value ?? ''),
    text
  )
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem(STORAGE_KEY)
    return saved === 'ar' ? 'ar' : 'en'
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const value = useMemo(() => {
    const t = (path, values) => {
      const current = getValue(translations[language], path)
      const fallback = getValue(translations.en, path)
      const text = current ?? fallback ?? path
      return typeof text === 'string' ? interpolate(text, values) : text
    }

    return {
      language,
      isArabic: language === 'ar',
      setLanguage,
      toggleLanguage: () => setLanguage((previous) => (previous === 'en' ? 'ar' : 'en')),
      t,
    }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}